# Assignment -3 

In [124]:
# Imports
import pandas as pd
import numpy as np
import tensorflow as tf
import keras as ks

# SK Learn Specific Imports
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Keras Specific Imports
from keras.utils.np_utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras import backend

In [125]:
# Import DataSet
data = pd.read_csv("assign3_dataset.csv")

In [126]:
# Original Data
data.head(5)

Unnamed: 0      ID               Name  Age  \
0           0  158023           L. Messi   31   
1           1   20801  Cristiano Ronaldo   33   
2           2  190871          Neymar Jr   26   
3           3  193080             De Gea   27   
4           4  192985       K. De Bruyne   27   

                                            Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1   https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2  https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3  https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4  https://cdn.sofifa.org/players/4/19/192985.png     Belgium   

                                  Flag  Overall  Potential  \
0  https://cdn.sofifa.org/flags/52.png       94         94   
1  https://cdn.sofifa.org/flags/38.png       94         94   
2  https://cdn.sofifa.org/flags/54.png       92         93   
3  https://cdn.sofifa.org/flags/45.png       91         93   
4   https://cdn.sofifa.org/flags/7.png       91         92   

                  Club  ... Composure Marking StandingTackle  SlidingTackle  \
0         FC Barcelona  ...      96.0    33.0           28.0           26.0   
1             Juventus  ...      95.0    28.0           31.0           23.0   
2  Paris Saint-Germain  ...      94.0    27.0           24.0           33.0   
3    Manchester United  ...      68.0    15.0           21.0           13.0   
4      Manchester City  ...      88.0    68.0           58.0           51.0   

  GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause  
0      6.0        11.0       15.0           14.0        8.0        €226.5M  
1      7.0        11.0       15.0           14.0       11.0        €127.1M  
2      9.0         9.0       15.0           15.0       11.0        €228.1M  
3     90.0        85.0       87.0           88.0       94.0        €138.6M  
4     15.0        13.0        5.0           10.0       13.0        €196.4M  

[5 rows x 89 columns]

In [127]:
# Filtered Data -> Not Nulls
nullval = pd.notnull(data['Position'])
data = data[nullval]
data.head()

Unnamed: 0      ID               Name  Age  \
0           0  158023           L. Messi   31   
1           1   20801  Cristiano Ronaldo   33   
2           2  190871          Neymar Jr   26   
3           3  193080             De Gea   27   
4           4  192985       K. De Bruyne   27   

                                            Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1   https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2  https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3  https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4  https://cdn.sofifa.org/players/4/19/192985.png     Belgium   

                                  Flag  Overall  Potential  \
0  https://cdn.sofifa.org/flags/52.png       94         94   
1  https://cdn.sofifa.org/flags/38.png       94         94   
2  https://cdn.sofifa.org/flags/54.png       92         93   
3  https://cdn.sofifa.org/flags/45.png       91         93   
4   https://cdn.sofifa.org/flags/7.png       91         92   

                  Club  ... Composure Marking StandingTackle  SlidingTackle  \
0         FC Barcelona  ...      96.0    33.0           28.0           26.0   
1             Juventus  ...      95.0    28.0           31.0           23.0   
2  Paris Saint-Germain  ...      94.0    27.0           24.0           33.0   
3    Manchester United  ...      68.0    15.0           21.0           13.0   
4      Manchester City  ...      88.0    68.0           58.0           51.0   

  GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause  
0      6.0        11.0       15.0           14.0        8.0        €226.5M  
1      7.0        11.0       15.0           14.0       11.0        €127.1M  
2      9.0         9.0       15.0           15.0       11.0        €228.1M  
3     90.0        85.0       87.0           88.0       94.0        €138.6M  
4     15.0        13.0        5.0           10.0       13.0        €196.4M  

[5 rows x 89 columns]

In [128]:
# Positions List
fwd = ["ST", "LW", "RW", "LF", "RF", "RS","LS", "CF"]
mid = ["CM","RCM","LCM", "CDM","RDM","LDM", "CAM", "LAM", "RAM", "RM", "LM"]
dfn = ["CB", "RCB", "LCB", "LWB", "RWB", "LB", "RB"]

In [129]:
# Assign Values to Positions
data.loc[data["Position"] == "GK", "Position"] = 0
data.loc[data["Position"].isin(dfn), "Position"] = 1
data.loc[data["Position"].isin(mid), "Position"] = 2
data.loc[data["Position"].isin(fwd), "Position"] = 3

In [130]:
# Count based on Values
data['Position'].value_counts()

2    6838
1    5866
3    3418
0    2025
Name: Position, dtype: int64

In [131]:
# Unique Values in Data
data['Position'].unique()

array([3, 0, 2, 1], dtype=object)

In [132]:
#Filtered Data (34 of 89 Columns)
data = data[["Position", 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes']]
data.head()

Position  Finishing  HeadingAccuracy  ShortPassing  Volleys  Dribbling  \
0        3       95.0             70.0          90.0     86.0       97.0   
1        3       94.0             89.0          81.0     87.0       88.0   
2        3       87.0             62.0          84.0     84.0       96.0   
3        0       13.0             21.0          50.0     13.0       18.0   
4        2       82.0             55.0          92.0     82.0       86.0   

   Curve  FKAccuracy  LongPassing  BallControl  ...  Penalties  Composure  \
0   93.0        94.0         87.0         96.0  ...       75.0       96.0   
1   81.0        76.0         77.0         94.0  ...       85.0       95.0   
2   88.0        87.0         78.0         95.0  ...       81.0       94.0   
3   21.0        19.0         51.0         42.0  ...       40.0       68.0   
4   85.0        83.0         91.0         91.0  ...       79.0       88.0   

   Marking  StandingTackle  SlidingTackle  GKDiving  GKHandling  GKKicking  \
0     33.0            28.0           26.0       6.0        11.0       15.0   
1     28.0            31.0           23.0       7.0        11.0       15.0   
2     27.0            24.0           33.0       9.0         9.0       15.0   
3     15.0            21.0           13.0      90.0        85.0       87.0   
4     68.0            58.0           51.0      15.0        13.0        5.0   

   GKPositioning  GKReflexes  
0           14.0         8.0  
1           14.0        11.0  
2           15.0        11.0  
3           88.0        94.0  
4           10.0        13.0  

[5 rows x 34 columns]

In [133]:
x = data.drop('Position',axis=1) # Drop Position Label from Filtered Data

In [134]:
# Fit x -> StandardScaler to Panda's DataFrame
ss = StandardScaler()
x = pd.DataFrame(ss.fit_transform(x))
y = data['Position']

In [135]:
x.head()

0         1         2         3         4         5         6   \
0  2.532391  1.018293  2.130190  2.434969  2.201010  2.491028  2.925359   
1  2.481180  2.111424  1.517765  2.491481  1.725114  1.838695  1.895584   
2  2.122700  0.558028  1.721906  2.321945  2.148132  2.219223  2.524891   
3 -1.666942 -1.800833 -0.591700 -1.690394 -1.976298 -1.422972 -1.365369   
4  1.866643  0.155296  2.266284  2.208922  1.619359  2.056139  2.296052   

         7         8         9   ...        23        24        25        26  \
0  2.236808  2.255005  1.767403  ...  1.684657  3.265669 -0.717896 -0.909470   
1  1.584271  2.135138  1.633444  ...  2.321491  3.178232 -0.969153 -0.770985   
2  1.649524  2.195072  1.968342  ...  2.066757  3.090795 -1.019405 -1.094116   
3 -0.112327 -0.981399 -0.509905  ... -0.544262  0.817436 -1.622423 -1.232601   
4  2.497823  1.955338  0.896668  ...  1.939390  2.566174  1.040907  0.475378   

         27        28        29        30        31        32  
0 -0.923850 -0.599889 -0.318983 -0.074713 -0.140266 -0.485159  
1 -1.064778 -0.543386 -0.318983 -0.074713 -0.140266 -0.318094  
2 -0.595016 -0.430379 -0.437259 -0.074713 -0.081569 -0.318094  
3 -1.534540  4.146377  4.057254  4.287959  4.203333  4.304052  
4  0.250555 -0.091360 -0.200706 -0.680640 -0.375055 -0.206717  

[5 rows x 33 columns]

In [136]:
y.head()

0    3
1    3
2    3
3    0
4    2
Name: Position, dtype: object

In [137]:
y_cat = to_categorical(y)

y_cat[:10]

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)

In [138]:
x_train, x_test, y_train, y_test = train_test_split(x.values, y_cat, test_size=0.2)

In [139]:
y.shape

(18147,)

In [140]:
x.shape

(18147, 33)

In [141]:
backend.clear_session()
model = Sequential()
model.add(Dense(60, input_shape = (33,), activation = "relu"))
model.add(Dense(15, activation = "relu"))
model.add(Dense(4, activation = "softmax"))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 60)                2040      
                                                                 
 dense_1 (Dense)             (None, 15)                915       
                                                                 
 dense_2 (Dense)             (None, 4)                 64        
                                                                 
Total params: 3,019
Trainable params: 3,019
Non-trainable params: 0
_________________________________________________________________


In [142]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [143]:
model.fit(x_train, y_train, verbose=1, epochs=25)

Epoch 1/25
454/454 [==============================] - 1s 2ms/step - loss: 0.2343 - accuracy: 0.8038
Epoch 2/25
454/454 [==============================] - 1s 2ms/step - loss: 0.1537 - accuracy: 0.8731
Epoch 3/25
454/454 [==============================] - 1s 1ms/step - loss: 0.1475 - accuracy: 0.8771
Epoch 4/25
454/454 [==============================] - 1s 2ms/step - loss: 0.1452 - accuracy: 0.8791
Epoch 5/25
454/454 [==============================] - 1s 1ms/step - loss: 0.1419 - accuracy: 0.8828
Epoch 6/25
454/454 [==============================] - 1s 1ms/step - loss: 0.1405 - accuracy: 0.8821
Epoch 7/25
454/454 [==============================] - 1s 2ms/step - loss: 0.1389 - accuracy: 0.8840
Epoch 8/25
454/454 [==============================] - 1s 1ms/step - loss: 0.1379 - accuracy: 0.8839
Epoch 9/25
454/454 [==============================] - 1s 1ms/step - loss: 0.1364 - accuracy: 0.8846
Epoch 10/25
454/454 [==============================] - 1s 2ms/step - loss: 0.1351 - accuracy: 0.8894

In [145]:
y_pred = model.predict(x_test)
y_pred

array([[7.6617379e-11, 9.9991703e-01, 8.3003608e-05, 1.4646543e-08],
       [1.0000000e+00, 1.4986236e-18, 4.7622896e-14, 1.5693391e-27],
       [3.5414984e-09, 9.9892247e-01, 1.0775432e-03, 7.1090409e-09],
       ...,
       [2.2755863e-08, 6.9427693e-01, 3.0567506e-01, 4.7992144e-05],
       [3.6329542e-08, 8.9529040e-04, 9.9883682e-01, 2.6789668e-04],
       [2.1382398e-08, 5.7697122e-05, 9.9906224e-01, 8.8001229e-04]],
      dtype=float32)

In [149]:
x_test[0]

array([-0.07938936,  0.09776234, -0.25146398, -0.16457468, -0.1784693 ,
       -0.06394403, -0.1067555 ,  0.01818058, -0.26219836, -1.44761961,
       -1.82414562, -1.99757577, -2.42366137, -1.20010412, -0.78126803,
       -1.44569719, -0.95757638, -0.18471921, -0.78458661, -0.51111593,
        0.30426015, -0.61250589, -0.94780063, -0.35321175, -0.58155372,
        0.03587692,  0.38305444,  0.29753148, -0.09136032, -0.25984435,
       -0.55945458, -0.19896334, -0.20671677])

In [148]:
y_test[0]

array([0., 1., 0., 0.], dtype=float32)

In [153]:
predict = model.predict(x_test)

In [162]:
predict > 0.65

array([[False,  True, False, False],
       [ True, False, False, False],
       [False,  True, False, False],
       ...,
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False,  True, False]])